site_name: Bolivian Virtual Observatory

nav:
  - Welcome Page: 'index.md'
  - Menú:
    - 1. Visión y Misión: '1.VisiónYMisión.md'
    - 2. Sobre el Proyecto: '2.SobreElProyecto.md'
    - 3. Convocatoria 2024: '3.2024Convocatoria.md'
    - 4. El Equipo: '4.Equipo.md'
    - 5. Ciencia: '5.Ciencia.md'
    - 6. Astrofotografía: '6.Astrofotografía.md'
    - 7. Contenido Académico del BVO: '7.ContenidoAcadémico.md'
    - 8. Contacto: '8.Contacto.md'

      
theme: readthedocs

extra_javascript:
  - extra.html
